name: Generate Datas

on:
  schedule:
    - cron: "* */2 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Rat Animation
      - uses: Platane/snk@master
        id: rat-gif
        with:
          github_user_name: name
          svg_out_path: dist/github-contribution-grid-rat.svg
          gif_out_path: dist/github-contribution-grid-rat.gif
          frames: 10
          commit_messages: "Added contribution"

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
